CRITICAL - 2023-08-29 00:00:18 --> readfile(C:\xampp\htdocs\app\writable\uploads\obras\17): Failed to open stream: Permission denied
in APPPATH\Controllers\Listados.php on line 31.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'readfile(C:\\xampp\\htdocs\\app\\writable\\uploads\\obras\\17): Failed to open stream: Permission denied', 'APPPATH\\Controllers\\Listados.php', 31)
 2 APPPATH\Controllers\Listados.php(31): readfile('FCPATH\\writable\\uploads\\obras\\17')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->qrdocumentos('24')
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-29 00:01:18 --> mime_content_type(C:\xampp\htdocs\app\writable\uploads\obras12/): Failed to open stream: No such file or directory
in APPPATH\Controllers\Listados.php on line 27.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mime_content_type(C:\\xampp\\htdocs\\app\\writable\\uploads\\obras12/): Failed to open stream: No such file or directory', 'APPPATH\\Controllers\\Listados.php', 27)
 2 APPPATH\Controllers\Listados.php(27): mime_content_type('FCPATH\\writable\\uploads\\obras12/')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->qrdocumentos('26')
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-29 15:46:51 --> mysqli_sql_exception: Table 'codigos.documentos_qr' doesn't exist in engine in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT * FROM d...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM d...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM d...')
#3 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#4 C:\xampp\htdocs\app\app\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\Listados->documentos()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-29 15:46:51 --> Table 'codigos.documentos_qr' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 APPPATH\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM documentos_qr where proceso_status=\'Enviado\'')
 2 APPPATH\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->documentos()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-29 15:47:24 --> mysqli_sql_exception: Table 'codigos.documentos_qr' doesn't exist in engine in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT * FROM d...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM d...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM d...')
#3 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#4 C:\xampp\htdocs\app\app\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\Listados->documentos()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-29 15:47:24 --> Table 'codigos.documentos_qr' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 APPPATH\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM documentos_qr where proceso_status=\'Enviado\'')
 2 APPPATH\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->documentos()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-29 15:47:25 --> mysqli_sql_exception: Table 'codigos.documentos_qr' doesn't exist in engine in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT * FROM d...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM d...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM d...')
#3 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#4 C:\xampp\htdocs\app\app\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\Listados->documentos()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-29 15:47:25 --> Table 'codigos.documentos_qr' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 APPPATH\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM documentos_qr where proceso_status=\'Enviado\'')
 2 APPPATH\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->documentos()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-29 15:58:22 --> mysqli_sql_exception: Table 'codigos.documentos_qr' doesn't exist in engine in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT * FROM d...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT * FROM d...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT * FROM d...')
#3 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#4 C:\xampp\htdocs\app\app\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\Listados->documentos()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-08-29 15:58:22 --> Table 'codigos.documentos_qr' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 APPPATH\Models\DocumentosModel.php(15): CodeIgniter\Database\BaseConnection->query('SELECT * FROM documentos_qr where proceso_status=\'Enviado\'')
 2 APPPATH\Controllers\Listados.php(18): App\Models\DocumentosModel->getdocumentosqr()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->documentos()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-29 17:50:16 --> mime_content_type(C:\xampp\htdocs\app\writable\uploads\obras12/): Failed to open stream: No such file or directory
in APPPATH\Controllers\Listados.php on line 27.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mime_content_type(C:\\xampp\\htdocs\\app\\writable\\uploads\\obras12/): Failed to open stream: No such file or directory', 'APPPATH\\Controllers\\Listados.php', 27)
 2 APPPATH\Controllers\Listados.php(27): mime_content_type('FCPATH\\writable\\uploads\\obras12/')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->qrdocumentos('1')
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-29 18:27:26 --> mysqli_sql_exception: Unknown column 'id' in 'where clause' in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `documen...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `documen...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `documen...')
#3 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `documen...', Array, false)
#4 C:\xampp\htdocs\app\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\app\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\app\system\Model.php(756): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\app\app\Controllers\Listados.php(39): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\Listados->revision1(1)
#9 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
#10 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-08-29 18:27:26 --> Unknown column 'id' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `documentosqr` SET `proceso_status` = :proceso_status:
WHERE `id` = :id:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 5 APPPATH\Controllers\Listados.php(39): CodeIgniter\Model->update()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->revision1(1)
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-29 23:46:08 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 924.
 1 SYSTEMPATH\BaseModel.php(924): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Listados.php(46): CodeIgniter\Model->update()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->revision2(1)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-29 23:47:21 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 924.
 1 SYSTEMPATH\BaseModel.php(924): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Listados.php(46): CodeIgniter\Model->update()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->revision2(1)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-29 23:48:56 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 924.
 1 SYSTEMPATH\BaseModel.php(924): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [])
 3 APPPATH\Controllers\Listados.php(46): CodeIgniter\Model->update()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Listados->revision2(1)
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
