ERROR - 2023-09-29 16:13:43 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=10260 in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 173)
#1 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#5 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#4 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#3 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2023-09-29 16:13:43 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=10260 in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 173)
#1 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#5 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#4 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#3 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-09-29 16:13:43 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `obra_expediente` INNER JOIN  universo on obra_expediente.obra= universo.universo_id GROUP by obra')
 3 APPPATH\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 16:13:43 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `obra_expediente` INNER JOIN  universo on obra_expediente.obra= universo.universo_id GROUP by obra')
 3 APPPATH\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-29 16:14:18 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#4 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#3 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-09-29 16:14:18 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `obra_expediente` INNER JOIN  universo on obra_expediente.obra= universo.universo_id GROUP by obra')
 3 APPPATH\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-29 16:16:25 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#4 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `...')
#3 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-09-29 16:16:25 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\ExpedienteModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM `obra_expediente` INNER JOIN  universo on obra_expediente.obra= universo.universo_id GROUP by obra')
 3 APPPATH\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->getExpedientes()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-29 17:22:19 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `documen...', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `documen...')
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `documen...')
#3 C:\xampp\htdocs\app\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `documen...', Array, false)
#4 C:\xampp\htdocs\app\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\app\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\app\system\Model.php(756): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\app\app\Controllers\FileUpload.php(166): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\FileUpload->incorrecto(3)
#9 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
#10 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-09-29 17:22:19 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `documentos_qr` SET `proceso_status` = :proceso_status:
WHERE `id_documento` = :id_documento:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 5 APPPATH\Controllers\FileUpload.php(166): CodeIgniter\Model->update()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->incorrecto(3)
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:26:12 --> Too few arguments to function App\Models\DocumentosModel::getdocumentossecretaria(), 0 passed in C:\xampp\htdocs\app\app\Controllers\FileUpload.php on line 237 and exactly 1 expected
in APPPATH\Models\DocumentosModel.php on line 23.
 1 APPPATH\Controllers\FileUpload.php(237): App\Models\DocumentosModel->getdocumentossecretaria()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->documentossecretaria()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:26:14 --> Too few arguments to function App\Models\DocumentosModel::getdocumentossecretaria(), 0 passed in C:\xampp\htdocs\app\app\Controllers\FileUpload.php on line 237 and exactly 1 expected
in APPPATH\Models\DocumentosModel.php on line 23.
 1 APPPATH\Controllers\FileUpload.php(237): App\Models\DocumentosModel->getdocumentossecretaria()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->documentossecretaria()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:26:17 --> Too few arguments to function App\Models\DocumentosModel::getdocumentossecretaria(), 0 passed in C:\xampp\htdocs\app\app\Controllers\FileUpload.php on line 237 and exactly 1 expected
in APPPATH\Models\DocumentosModel.php on line 23.
 1 APPPATH\Controllers\FileUpload.php(237): App\Models\DocumentosModel->getdocumentossecretaria()
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->documentossecretaria()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:43:29 --> Class "Mpdf\Mpdf" not found
in APPPATH\Controllers\FileUpload.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->generatePDF(14)
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:45:01 --> Class "App\Controllers\MpdfMpdf" not found
in APPPATH\Controllers\FileUpload.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->generatePDF(14)
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:47:43 --> require_once(C:\xampp\htdocs\app\app\Controllers/pdf/autoload.php): Failed to open stream: No such file or directory
in APPPATH\Controllers\FileUpload.php on line 252.
 1 APPPATH\Controllers\FileUpload.php(252): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require_once(C:\\xampp\\htdocs\\app\\app\\Controllers/pdf/autoload.php): Failed to open stream: No such file or directory', 'APPPATH\\Controllers\\FileUpload.php', 252)
 2 APPPATH\Controllers\FileUpload.php(252): require_once()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->generatePDF(14)
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:49:18 --> require_once(C:\xampp\htdocs\app\app\Controllers/pdf/autoload.php): Failed to open stream: No such file or directory
in APPPATH\Controllers\FileUpload.php on line 252.
 1 APPPATH\Controllers\FileUpload.php(252): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require_once(C:\\xampp\\htdocs\\app\\app\\Controllers/pdf/autoload.php): Failed to open stream: No such file or directory', 'APPPATH\\Controllers\\FileUpload.php', 252)
 2 APPPATH\Controllers\FileUpload.php(252): require_once()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->generatePDF(14)
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 20:49:45 --> Class "App\Controllers\mPDF" not found
in APPPATH\Controllers\FileUpload.php on line 253.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->generatePDF(14)
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:27:50 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:28:15 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:28:16 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:28:32 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:28:34 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:29:08 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:29:10 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:29:25 --> Undefined property: stdClass::$totaldocumentos
in APPPATH\Views\expediente.php on line 69.
 1 APPPATH\Views\expediente.php(69): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumentos', 'APPPATH\\Views\\expediente.php', 69)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:32:05 --> Undefined property: stdClass::$totaldocumento
in APPPATH\Views\expediente.php on line 70.
 1 APPPATH\Views\expediente.php(70): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$totaldocumento', 'APPPATH\\Views\\expediente.php', 70)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:50:29 --> syntax error, unexpected token "endforeach", expecting end of file
in APPPATH\Views\expediente.php on line 87.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 3 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:50:55 --> syntax error, unexpected token "endforeach", expecting end of file
in APPPATH\Views\expediente.php on line 87.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 3 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 22:51:37 --> Undefined variable $k
in APPPATH\Views\expediente.php on line 71.
 1 APPPATH\Views\expediente.php(71): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $k', 'APPPATH\\Views\\expediente.php', 71)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\expediente.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('expediente', [], true)
 5 APPPATH\Controllers\ExpedienteObra.php(34): view('expediente', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-29 23:58:19 --> Undefined variable $idtitulo
in APPPATH\Models\ExpedienteModel.php on line 25.
 1 APPPATH\Models\ExpedienteModel.php(25): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $idtitulo', 'APPPATH\\Models\\ExpedienteModel.php', 25)
 2 APPPATH\Controllers\ExpedienteObra.php(32): App\Models\ExpedienteModel->totalpartida2()
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->expedientes()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
