ERROR - 2023-10-10 04:12:24 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#4 C:\xampp\htdocs\app\app\Controllers\FileUpload.php(115): App\Models\DocumentosModel->getdocumentosejecutora()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\FileUpload->documentosejecutora()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\DocumentosModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT * FROM d...')
#3 C:\xampp\htdocs\app\app\Controllers\FileUpload.php(115): App\Models\DocumentosModel->getdocumentosejecutora()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\FileUpload->documentosejecutora()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-10 04:12:24 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\DocumentosModel.php(20): CodeIgniter\Database\BaseConnection->query('SELECT * FROM documentos_qr where proceso_status=\'Ilegible\'')
 3 APPPATH\Controllers\FileUpload.php(115): App\Models\DocumentosModel->getdocumentosejecutora()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\FileUpload->documentosejecutora()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileUpload))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-10 04:12:26 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'documentos', 3306, '', 0)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(47): CodeIgniter\Database\BaseConnection->query('select cat_unid...')
#4 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->expedienteXejecutoraenviadosTotales()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->ejecutoraexpediente()
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#7 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\app\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\app\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\app\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\app\app\Models\ExpedienteModel.php(47): CodeIgniter\Database\BaseConnection->query('select cat_unid...')
#3 C:\xampp\htdocs\app\app\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->expedienteXejecutoraenviadosTotales()
#4 C:\xampp\htdocs\app\system\CodeIgniter.php(934): App\Controllers\ExpedienteObra->ejecutoraexpediente()
#5 C:\xampp\htdocs\app\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
#6 C:\xampp\htdocs\app\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\app\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-10 04:12:26 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\ExpedienteModel.php(47): CodeIgniter\Database\BaseConnection->query('select cat_unidad_ejecutora.ejecutora_id,ejecutora_nombre,
        (select sum(obra_expediente.existencia=\'SI\'))as totaleviadosejecutora,
        (select count(universo.universo_id) GROUP by universo.unidad_ejecutora) as total_X_ejecutora,
        (select count(num_expediente)) as totalexpedienteEjecutora 
        from cat_unidad_ejecutora 
        LEFT JOIN universo on cat_unidad_ejecutora.ejecutora_id=universo.unidad_ejecutora
        LEFT JOIN obra_expediente ON universo.universo_id=obra_expediente.obra
        GROUP by universo.unidad_ejecutora
        ORDER by totalexpedienteEjecutora DESC')
 3 APPPATH\Controllers\ExpedienteObra.php(30): App\Models\ExpedienteModel->expedienteXejecutoraenviadosTotales()
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ExpedienteObra->ejecutoraexpediente()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ExpedienteObra))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
